<?php
$this->htmlElement('body')->appendAttribute('class', 'challenge-fail');
$this->headScript()->appendFile($this->assetUrl('js/challenge-fail.js', 'Search'));
$escape = $this->plugin('escapeHtml');

?>
<div id="challenge-page" style="display: none">
    <!-- Modal -->
    <div class="modal fade" id="challengeModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="challengeLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content border">
                <div class="modal-body p-4 p-lg-5">
                    <div class="container-fluid p-0">
                        <div class="row">
                            <div class="col" id="challenge-head">
                                <h1 class="text-center" id="challengeLabel">
                                    Too many requests...
                                </h1>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p id="challengeRights">
                                Sorry, there's been an unusual number of requests from your browser. If you believe you have come to this page in an error, please restart your browser and try again. Or please contact us at <a href="mailto:repository@fitnyc.edu">repository@fitnyc.edu</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>